from __future__ import annotations
import json,re
import pandas as pd
import plotly.express as px
import streamlit as st
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

st.set_page_config(page_title='MeetingLens AI',page_icon='◉',layout='wide',initial_sidebar_state='expanded')
HERO='https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1900&q=90'
SECOND='https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1500&q=88'
CSS=r'''<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap');
:root{--bg:#0d0f11;--panel:#191d21;--text:#f2efe9;--muted:#98a0a5;--line:rgba(255,255,255,.08);--bronze:#b99764;--gold:#d5b681;--sage:#8fa79c;--steel:#8997a3}
*{box-sizing:border-box}html,body,[class*=css]{font-family:Inter,sans-serif}.stApp{color:var(--text);background:radial-gradient(circle at 8% 5%,rgba(213,182,129,.06),transparent 22%),radial-gradient(circle at 93% 22%,rgba(143,167,156,.045),transparent 25%),linear-gradient(180deg,#0c0e10,#121518 52%,#0d0f11)}[data-testid=stHeader]{background:transparent}.block-container{max-width:1540px;padding-top:1rem;padding-bottom:5rem}[data-testid=stSidebar]{background:linear-gradient(180deg,#111417,#0d0f11);border-right:1px solid var(--line)}
.ambient{position:fixed;inset:0;pointer-events:none;overflow:hidden}.orb{position:absolute;border-radius:50%;filter:blur(70px);opacity:.13;animation:drift 18s ease-in-out infinite alternate}.o1{width:330px;height:330px;background:#b99764;left:-120px;top:8%}.o2{width:400px;height:400px;background:#6e8179;right:-160px;top:30%;animation-duration:24s}.o3{width:260px;height:260px;background:#74818c;left:42%;bottom:-120px;animation-duration:20s}@keyframes drift{to{transform:translate(28px,20px) scale(1.08)}}
.brand{display:flex;align-items:center;gap:.75rem;margin:.15rem 0 1.3rem;animation:up .7s ease both}.logo{width:44px;height:44px;border-radius:15px;display:grid;place-items:center;border:1px solid rgba(213,182,129,.28);background:linear-gradient(145deg,#282d31,#171a1d);color:var(--gold);font-family:Manrope;font-weight:800;box-shadow:0 12px 34px rgba(0,0,0,.28)}.name{font-family:Manrope;font-size:1.08rem;font-weight:800;letter-spacing:-.035em}.name span{color:var(--gold)}.micro{font-size:.65rem;text-transform:uppercase;letter-spacing:.15em;color:#737b80;font-weight:700}.side{border:1px solid var(--line);background:rgba(255,255,255,.018);border-radius:17px;padding:1rem;margin-top:.85rem;transition:.25s}.side:hover{transform:translateY(-2px);border-color:rgba(213,182,129,.17)}.side strong{display:block;margin-top:.3rem;font-size:.84rem}.line{height:1px;background:linear-gradient(90deg,rgba(213,182,129,.45),transparent);margin-top:.7rem}
.top{display:flex;align-items:center;justify-content:space-between;padding:.35rem 0 1rem;border-bottom:1px solid var(--line);margin-bottom:1.1rem;animation:up .65s ease both}.eye{font-size:.68rem;text-transform:uppercase;letter-spacing:.15em;color:#7e858a;font-weight:700}.live{display:inline-flex;align-items:center;gap:.5rem;padding:.46rem .72rem;border-radius:999px;border:1px solid rgba(143,167,156,.22);background:rgba(143,167,156,.055);color:#becbc5;font-size:.72rem;font-weight:650}.dot{width:7px;height:7px;border-radius:50%;background:var(--sage);animation:pulse 2.2s infinite}@keyframes pulse{0%,100%{opacity:.45;box-shadow:0 0 0 0 rgba(143,167,156,.2)}50%{opacity:1;box-shadow:0 0 0 7px transparent}}
.hero{position:relative;display:grid;grid-template-columns:1.03fr .97fr;min-height:575px;overflow:hidden;border:1px solid var(--line);border-radius:32px;background:linear-gradient(135deg,#181c20,#111416);box-shadow:0 40px 110px rgba(0,0,0,.3);isolation:isolate;animation:heroIn .9s cubic-bezier(.2,.8,.2,1) both}.hero:before{content:'';position:absolute;inset:0;background:linear-gradient(120deg,transparent 20%,rgba(255,255,255,.025) 42%,transparent 58%);transform:translateX(-120%);animation:sweep 9s ease-in-out infinite;z-index:8;pointer-events:none}@keyframes sweep{0%,58%{transform:translateX(-120%)}78%,100%{transform:translateX(120%)}}@keyframes heroIn{from{opacity:0;transform:translateY(18px) scale(.992)}to{opacity:1;transform:none}}
.hleft{position:relative;padding:4.4rem 3.5rem 3.4rem;display:flex;flex-direction:column;justify-content:center;z-index:3}.hleft:after{content:'';position:absolute;width:440px;height:440px;border-radius:50%;left:-260px;bottom:-260px;border:1px solid rgba(213,182,129,.12);box-shadow:0 0 0 44px rgba(213,182,129,.018),0 0 0 88px rgba(213,182,129,.01);animation:orbit 16s ease-in-out infinite alternate}@keyframes orbit{to{transform:translate(28px,-16px) scale(1.04)}}.label{display:inline-flex;width:max-content;padding:.47rem .7rem;border-radius:999px;border:1px solid rgba(213,182,129,.2);background:rgba(185,151,100,.045);color:#d4bea0;font-size:.65rem;text-transform:uppercase;letter-spacing:.125em;font-weight:700;margin-bottom:1.25rem;animation:up .8s .1s ease both}.hero h1{font-family:Manrope;font-size:clamp(3rem,5.2vw,6rem);line-height:.91;letter-spacing:-.07em;margin:0;max-width:780px;font-weight:800;animation:up .85s .18s ease both}.hero h1 em{font-style:normal;color:var(--gold);font-weight:700;position:relative}.hero h1 em:after{content:'';position:absolute;left:0;right:0;bottom:-8px;height:1px;background:linear-gradient(90deg,var(--gold),transparent);transform-origin:left;animation:grow 1.2s .65s ease both}@keyframes grow{from{transform:scaleX(0)}to{transform:scaleX(1)}}.hero p{font-size:1rem;line-height:1.78;color:#aeb4b7;max-width:610px;margin:1.35rem 0 0;animation:up .85s .26s ease both}.chips{display:flex;flex-wrap:wrap;gap:.56rem;margin-top:1.42rem;animation:up .85s .34s ease both}.chip{font-size:.72rem;color:#c7cccf;border:1px solid var(--line);border-radius:999px;padding:.46rem .68rem;background:rgba(255,255,255,.018);transition:.2s}.chip:hover{border-color:rgba(213,182,129,.2);color:#e3d8c8;transform:translateY(-2px)}.signal{display:flex;align-items:center;gap:.8rem;margin-top:1.75rem;animation:up .85s .42s ease both}.signal span{font-size:.64rem;text-transform:uppercase;letter-spacing:.12em;color:#747d82;font-weight:700}.sigline{height:1px;flex:1;max-width:260px;background:linear-gradient(90deg,rgba(213,182,129,.8),rgba(143,167,156,.45),transparent);background-size:200% 100%;animation:flow 4s linear infinite}@keyframes flow{to{background-position:-200% 0}}
.hright{position:relative;min-height:575px;background-image:linear-gradient(180deg,rgba(14,16,18,.05),rgba(14,16,18,.72)),url('''+HERO+r''');background-size:104% auto;background-position:center;overflow:hidden;animation:breathe 18s ease-in-out infinite alternate}@keyframes breathe{to{background-size:111% auto}}.hright:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,#181c20 0%,rgba(24,28,32,.35) 18%,transparent 46%)}.float{position:absolute;z-index:4;border:1px solid rgba(255,255,255,.11);background:rgba(16,18,20,.72);backdrop-filter:blur(18px);box-shadow:0 18px 55px rgba(0,0,0,.28);border-radius:19px;padding:1rem 1.05rem;animation:floating 6s ease-in-out infinite}.f1{top:2rem;right:2rem;width:205px}.f2{top:8.9rem;right:3.6rem;width:175px;animation-delay:-2.2s}.f3{bottom:2rem;left:2rem;right:2rem;animation-duration:7.5s;animation-delay:-1.4s}@keyframes floating{50%{transform:translateY(-7px)}}.flabel{font-size:.6rem;text-transform:uppercase;letter-spacing:.12em;color:#7e868b;font-weight:700}.fvalue{font-family:Manrope;font-size:1.35rem;font-weight:800;letter-spacing:-.045em;margin-top:.24rem}.fnote{font-size:.71rem;color:#aeb4b7;margin-top:.22rem}.wave{display:flex;align-items:center;gap:4px;height:38px;margin-top:.45rem}.wave i{display:block;width:3px;border-radius:99px;background:linear-gradient(180deg,var(--gold),var(--sage));animation:wave 1.7s ease-in-out infinite;opacity:.8}.wave i:nth-child(2n){animation-delay:.14s}.wave i:nth-child(3n){animation-delay:.29s}.wave i:nth-child(5n){animation-delay:.41s}@keyframes wave{0%,100%{height:6px;opacity:.32}50%{height:32px;opacity:.92}}
.section{margin:1.45rem 0 .8rem;animation:up .75s ease both}.section h3{font-family:Manrope;margin:0;font-size:1.15rem;letter-spacing:-.03em}.section p{margin:.25rem 0 0;color:#7f878c;font-size:.76rem}.idx{font-size:.64rem;letter-spacing:.15em;text-transform:uppercase;color:#737b80;font-weight:700}.kpi{position:relative;overflow:hidden;border:1px solid var(--line);border-radius:21px;padding:1.2rem 1.22rem;min-height:142px;background:linear-gradient(180deg,rgba(28,32,36,.92),rgba(20,23,26,.94));transition:.28s;animation:up .7s ease both}.kpi:hover{transform:translateY(-6px);border-color:rgba(213,182,129,.2);box-shadow:0 22px 55px rgba(0,0,0,.24)}.kpi:after{content:'';position:absolute;inset:0;background:linear-gradient(115deg,transparent 24%,rgba(255,255,255,.035) 48%,transparent 68%);transform:translateX(-130%);transition:.8s}.kpi:hover:after{transform:translateX(130%)}.kl{font-size:.63rem;text-transform:uppercase;letter-spacing:.12em;color:#7f878c;font-weight:700}.kv{font-family:Manrope;font-size:2.06rem;font-weight:800;letter-spacing:-.058em;margin:.4rem 0 .18rem}.kn{font-size:.74rem;color:#8e969b}.badge{position:absolute;right:1rem;top:1rem;width:7px;height:7px;border-radius:50%;background:var(--bronze);box-shadow:0 0 0 5px rgba(185,151,100,.055)}.meter{height:3px;border-radius:99px;background:rgba(255,255,255,.05);overflow:hidden;margin-top:.82rem}.meter span{display:block;height:100%;border-radius:99px;background:linear-gradient(90deg,var(--bronze),var(--sage));transform-origin:left;animation:meter 1.25s .2s ease both}@keyframes meter{from{transform:scaleX(.08);opacity:.2}to{transform:scaleX(1);opacity:1}}
.panel{position:relative;overflow:hidden;border:1px solid var(--line);border-radius:23px;background:linear-gradient(180deg,rgba(25,29,33,.86),rgba(20,23,26,.88));padding:1.35rem;box-shadow:inset 0 1px 0 rgba(255,255,255,.02);animation:up .78s ease both}.pt{font-family:Manrope;font-size:1.03rem;font-weight:760;letter-spacing:-.025em}.ps{font-size:.75rem;color:#858d92;margin:.26rem 0 1rem}.moment{display:grid;grid-template-columns:60px 1fr;gap:.82rem;padding:.9rem .18rem;border-bottom:1px solid rgba(255,255,255,.055);transition:.22s}.moment:last-child{border-bottom:0}.moment:hover{padding-left:.55rem;background:linear-gradient(90deg,rgba(185,151,100,.035),transparent)}.time{font-size:.65rem;color:var(--gold);padding-top:.18rem;font-weight:700}.mh{font-size:.82rem;font-weight:650}.tag{display:inline-block;font-size:.55rem;text-transform:uppercase;letter-spacing:.07em;border:1px solid rgba(185,151,100,.16);background:rgba(185,151,100,.05);color:#cbb18b;padding:.18rem .38rem;border-radius:999px;margin-left:.32rem}.mt{font-size:.76rem;line-height:1.58;color:#9ea5aa;margin-top:.24rem}.decision{padding:.9rem .96rem;margin:.72rem 0;border-radius:16px;background:rgba(255,255,255,.015);border:1px solid rgba(255,255,255,.055);transition:.22s}.decision:hover{transform:translateX(4px);border-color:rgba(213,182,129,.16)}.conf,.owner{display:inline-flex;font-size:.57rem;margin-top:.45rem;padding:.2rem .4rem;border-radius:999px;border:1px solid rgba(143,167,156,.14);color:#b8c9c1;background:rgba(143,167,156,.055)}.owner{margin-left:.35rem;border-color:rgba(137,151,163,.13);color:#b8c0c8;background:rgba(137,151,163,.055)}.risk{display:flex;justify-content:space-between;gap:1rem;padding:.78rem .15rem;border-bottom:1px solid rgba(255,255,255,.05)}.risk:last-child{border-bottom:0}.sev{font-size:.56rem;text-transform:uppercase;letter-spacing:.09em;color:#c5b08d;border:1px solid rgba(185,151,100,.15);border-radius:999px;padding:.2rem .4rem}
.visual{position:relative;min-height:350px;border-radius:23px;overflow:hidden;background-image:linear-gradient(180deg,rgba(14,16,18,.06),rgba(14,16,18,.84)),url('''+SECOND+r''');background-size:103% auto;background-position:center;animation:vzoom 16s ease-in-out infinite alternate}@keyframes vzoom{to{background-size:110% auto}}.vcopy{position:absolute;left:1.3rem;right:1.3rem;bottom:1.2rem}.vbig{font-family:Manrope;font-size:1.5rem;font-weight:800;letter-spacing:-.045em;line-height:1.06}.vnote{font-size:.74rem;color:#b8bdc0;margin-top:.42rem}.strip{display:grid;grid-template-columns:repeat(3,1fr);gap:.65rem;margin-top:.8rem}.mini{border:1px solid var(--line);border-radius:14px;padding:.8rem;background:rgba(255,255,255,.014)}.mini b{font-size:.92rem}.mini span{display:block;color:#858d92;font-size:.66rem;margin-top:.18rem}
.stTabs [data-baseweb=tab-list]{gap:.45rem;border-bottom:1px solid var(--line);padding-bottom:.56rem}.stTabs [data-baseweb=tab]{font-size:.68rem;border-radius:10px;padding:.5rem .8rem;background:rgba(255,255,255,.018);border:1px solid var(--line);color:#9da4a8;transition:.2s}.stTabs [data-baseweb=tab]:hover{border-color:rgba(213,182,129,.16);color:#d5cab9}.stTabs [aria-selected=true]{background:rgba(185,151,100,.085)!important;color:#d8c8ad!important;border-color:rgba(185,151,100,.2)!important}[data-testid=stFileUploader]{border:1px dashed rgba(213,182,129,.17);border-radius:16px;padding:.3rem;background:rgba(185,151,100,.016)}[data-testid=stDataFrame]{border:1px solid var(--line);border-radius:16px;overflow:hidden}.stTextInput input{background:#171b1f!important;border:1px solid rgba(255,255,255,.08)!important;color:#eeeae3!important;border-radius:12px!important}.foot{text-align:center;color:#596065;font-size:.63rem;margin-top:3rem;padding-top:1.25rem;border-top:1px solid rgba(255,255,255,.045);letter-spacing:.08em}@keyframes up{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:none}}@media(max-width:1100px){.hero{grid-template-columns:1fr}.hright{min-height:440px}.hleft{padding:3.2rem 1.8rem}.f1,.f2{display:none}.hero h1{font-size:clamp(2.9rem,9.5vw,5rem)}}@media(max-width:720px){.block-container{padding-left:.75rem;padding-right:.75rem}.hero{border-radius:24px}.hleft{padding:2.4rem 1.25rem}.hright{min-height:360px}.f3{left:1rem;right:1rem;bottom:1rem}.strip{grid-template-columns:1fr}}
</style>'''
st.markdown(CSS,unsafe_allow_html=True)
st.markdown('<div class="ambient"><span class="orb o1"></span><span class="orb o2"></span><span class="orb o3"></span></div>',unsafe_allow_html=True)
DEMO={'title':'Product Intelligence Weekly','duration_min':47,'summary':'The team aligned on launch readiness, analytics fixes, and ownership for the next release.','participants':[{'name':'Maya','talk_pct':31},{'name':'Noah','talk_pct':27},{'name':'Lina','talk_pct':23},{'name':'Omar','talk_pct':19}],'segments':[{'minute':3,'speaker':'Maya','kind':'context','text':'We need to leave today with one launch decision and clear owners.','sentiment':'neutral'},{'minute':12,'speaker':'Noah','kind':'risk','text':'The analytics patch is still blocking our final validation.','sentiment':'negative'},{'minute':21,'speaker':'Lina','kind':'decision','text':'We will keep the Friday release if analytics passes tomorrow morning.','sentiment':'positive'},{'minute':29,'speaker':'Omar','kind':'action','text':'I will own the analytics validation and post results before noon.','sentiment':'positive'},{'minute':38,'speaker':'Maya','kind':'decision','text':'Support will receive the rollout notes before the release window.','sentiment':'positive'}],'decisions':[{'title':'Keep Friday release target','detail':'Conditional on analytics validation tomorrow morning.','confidence':.94},{'title':'Share rollout notes with Support','detail':'Notes must land before the release window.','confidence':.91}],'actions':[{'task':'Validate analytics patch','owner':'Omar','due':'Tomorrow 12:00','status':'Open'},{'task':'Prepare rollout notes','owner':'Maya','due':'Friday 09:00','status':'Open'}],'risks':[{'title':'Analytics validation delay','severity':'Medium'}]}
AN=SentimentIntensityAnalyzer()
def classify(t):
 s=AN.polarity_scores(t or '')['compound'];return 'positive' if s>=.18 else 'negative' if s<=-.18 else 'neutral'
def health(m):
 p=[x.get('talk_pct',0) for x in m.get('participants',[])];bal=80 if not p else max(0,100-(max(p)-min(p))*2);clar=min(100,55+len(m.get('decisions',[]))*12+len(m.get('actions',[]))*7);seg=m.get('segments',[]);pos=sum(1 for x in seg if x.get('sentiment')=='positive');sent=int(pos/max(1,len(seg))*100);return {'overall':round(bal*.3+clar*.45+sent*.25),'clarity':int(clar),'balance':int(bal),'sentiment':sent}
def tokens(t):return {x for x in re.findall(r"[a-zA-Z0-9']+",(t or '').lower()) if len(x)>2}
def search(m,q):
 q=tokens(q);out=[]
 for s in m.get('segments',[]):
  score=len(q & tokens(' '.join([s.get('speaker',''),s.get('kind',''),s.get('text','')])))
  if score:out.append((score,s))
 return [s for _,s in sorted(out,key=lambda x:-x[0])]
def load(f):
 try:
  d=json.load(f)
  for s in d.get('segments',[]):s['sentiment']=s.get('sentiment') or classify(s.get('text',''))
  return d,None
 except Exception as e:return None,str(e)
with st.sidebar:
 st.markdown('<div class="brand"><div class="logo">M</div><div class="name">MeetingLens <span>AI</span></div></div>',unsafe_allow_html=True);st.markdown('<div class="micro">Conversation intelligence</div>',unsafe_allow_html=True);up=st.file_uploader('Upload meeting JSON',type=['json']);st.markdown('<div class="side"><div class="micro">Focus</div><strong>Decision & action intelligence</strong><div class="line"></div></div>',unsafe_allow_html=True);st.markdown('<div class="side"><div class="micro">Experience</div><strong>Unified Streamlit workspace</strong><div class="line"></div></div>',unsafe_allow_html=True)
m=DEMO
if up:
 d,e=load(up)
 if d:m=d;st.sidebar.success('Meeting loaded')
 else:st.sidebar.error(f'Invalid JSON: {e}')
st.markdown('<div class="top"><div class="eye">Meeting intelligence / live workspace</div><div class="live"><span class="dot"></span>engine online</div></div>',unsafe_allow_html=True)
tabs=st.tabs(['Overview','Meeting Analyzer','Knowledge Search','Insights'])
with tabs[0]:
 h=health(m);bars=''.join('<i></i>' for _ in range(22));st.markdown(f'''<div class="hero"><div class="hleft"><div class="label">◉ AI meeting intelligence</div><h1>Turn conversation into <em>clarity.</em></h1><p>{m.get('summary','Turn conversations into decisions, ownership and searchable memory.')}</p><div class="chips"><span class="chip">{m.get('title','Meeting')}</span><span class="chip">{m.get('duration_min',0)} min</span><span class="chip">{len(m.get('participants',[]))} participants</span></div><div class="signal"><span>decision signal</span><div class="sigline"></div></div></div><div class="hright"><div class="float f1"><div class="flabel">Meeting health</div><div class="fvalue">{h['overall']}/100</div><div class="fnote">Clarity, balance and tone</div></div><div class="float f2"><div class="flabel">Actions</div><div class="fvalue">{len(m.get('actions',[]))}</div><div class="fnote">Assigned next steps</div></div><div class="float f3"><div class="flabel">Conversation pulse</div><div class="fvalue">Decision signal detected</div><div class="wave">{bars}</div></div></div></div>''',unsafe_allow_html=True)
 st.markdown('<div class="section"><div class="idx">01 / Intelligence snapshot</div><h3>What this meeting produced</h3><p>Fast read on clarity, ownership and follow-through.</p></div>',unsafe_allow_html=True);vals=[('Meeting health',f"{h['overall']}/100",'Clarity, balance & tone',h['overall']),('Decisions',len(m.get('decisions',[])),'Captured commitments',min(100,len(m.get('decisions',[]))*35+25)),('Action items',len(m.get('actions',[])),'Owners & deadlines',min(100,len(m.get('actions',[]))*35+20)),('Risks',len(m.get('risks',[])),'Needs follow-up',42)];cols=st.columns(4)
 for c,(a,b,n,z) in zip(cols,vals):
  with c:st.markdown(f'<div class="kpi"><span class="badge"></span><div class="kl">{a}</div><div class="kv">{b}</div><div class="kn">{n}</div><div class="meter"><span style="width:{z}%"></span></div></div>',unsafe_allow_html=True)
 st.markdown('<div class="section"><div class="idx">02 / Conversation map</div><h3>Moments that changed direction</h3><p>Signals worth revisiting without replaying the whole call.</p></div>',unsafe_allow_html=True);a,b=st.columns([1.23,.77])
 with a:
  st.markdown('<div class="panel"><div class="pt">Key moments</div><div class="ps">Decisions, risks, context and ownership.</div>',unsafe_allow_html=True)
  for s in m.get('segments',[]):st.markdown(f'<div class="moment"><div class="time">{str(s.get("minute",0)).zfill(2)}:00</div><div><div class="mh">{s.get("speaker","Speaker")} <span class="tag">{s.get("kind","moment")}</span></div><div class="mt">{s.get("text","")}</div></div></div>',unsafe_allow_html=True)
  st.markdown('</div>',unsafe_allow_html=True)
 with b:
  st.markdown('<div class="panel"><div class="pt">Speaker balance</div><div class="ps">Share of speaking time.</div>',unsafe_allow_html=True);df=pd.DataFrame(m.get('participants',[]))
  if not df.empty:
   fig=px.pie(df,values='talk_pct',names='name',hole=.76,color_discrete_sequence=['#b99764','#8fa79c','#8997a3','#c0b5a6']);fig.update_traces(textinfo='none',hovertemplate='%{label}<br>%{value}%<extra></extra>');fig.update_layout(height=310,margin=dict(l=0,r=0,t=0,b=0),showlegend=False,paper_bgcolor='rgba(0,0,0,0)',font_color='#f2efe9');st.plotly_chart(fig,use_container_width=True,config={'displayModeBar':False})
  st.markdown('</div>',unsafe_allow_html=True)
with tabs[1]:
 st.markdown('<div class="section"><div class="idx">Analyzer</div><h3>Meeting intelligence report</h3><p>Commitments, next actions and unresolved risks.</p></div>',unsafe_allow_html=True);a,b=st.columns(2)
 with a:
  st.markdown('<div class="panel"><div class="pt">Decisions captured</div><div class="ps">Commitments with confidence.</div>',unsafe_allow_html=True)
  for d in m.get('decisions',[]):st.markdown(f'<div class="decision"><strong>✓ {d.get("title","Decision")}</strong><div class="mt">{d.get("detail","")}</div><span class="conf">{round(float(d.get("confidence",0))*100)}% confidence</span></div>',unsafe_allow_html=True)
  st.markdown('</div>',unsafe_allow_html=True)
 with b:
  st.markdown('<div class="panel"><div class="pt">Action radar</div><div class="ps">What needs to happen next.</div>',unsafe_allow_html=True)
  for x in m.get('actions',[]):st.markdown(f'<div class="decision"><strong>{x.get("task","Task")}</strong><span class="owner">{x.get("owner","Unassigned")}</span><div class="mt">Due {x.get("due","TBD")} · {x.get("status","Open")}</div></div>',unsafe_allow_html=True)
  st.markdown('</div>',unsafe_allow_html=True)
 st.write('');l,r=st.columns([.68,.32])
 with l:st.dataframe(pd.DataFrame(m.get('segments',[])),use_container_width=True,hide_index=True)
 with r:
  st.markdown('<div class="panel"><div class="pt">Risk watch</div><div class="ps">Open blockers and concerns.</div>',unsafe_allow_html=True)
  for x in m.get('risks',[]):st.markdown(f'<div class="risk"><span>{x.get("title","Risk")}</span><span class="sev">{x.get("severity","Open")}</span></div>',unsafe_allow_html=True)
  st.markdown('</div>',unsafe_allow_html=True)
with tabs[2]:
 st.markdown('<div class="section"><div class="idx">Knowledge memory</div><h3>Search what the meeting knows</h3><p>Find topics, owners, risks and decisions instantly.</p></div>',unsafe_allow_html=True);q=st.text_input('Ask the meeting memory',placeholder='e.g. analytics patch, Friday release, Support...')
 if q:
  rr=search(m,q)
  if not rr:st.info('No matching moment found.')
  for s in rr:st.markdown(f'<div class="panel"><div class="pt">{s.get("speaker","Speaker")} · {s.get("minute",0)}:00 <span class="tag">{s.get("kind","moment")}</span></div><div class="mt">{s.get("text","")}</div></div><br>',unsafe_allow_html=True)
 else:st.info('Type a topic above to search inside the meeting.')
with tabs[3]:
 st.markdown('<div class="section"><div class="idx">Insights</div><h3>Read the meeting at a glance</h3><p>Clarity, participation, tone and follow-through.</p></div>',unsafe_allow_html=True);h=health(m);c1,c2,c3,c4=st.columns(4);c1.metric('Overall',f"{h['overall']}/100");c2.metric('Clarity',f"{h['clarity']}/100");c3.metric('Balance',f"{h['balance']}/100");c4.metric('Positive tone',f"{h['sentiment']}%");l,r=st.columns([.64,.36])
 with l:
  seg=pd.DataFrame(m.get('segments',[]))
  if not seg.empty:
   cnt=seg['sentiment'].value_counts().rename_axis('sentiment').reset_index(name='count');fig=px.bar(cnt,x='sentiment',y='count',color='sentiment',color_discrete_map={'positive':'#8fa79c','neutral':'#8997a3','negative':'#9f7f6d'});fig.update_layout(height=350,paper_bgcolor='rgba(0,0,0,0)',plot_bgcolor='rgba(0,0,0,0)',font_color='#f2efe9',showlegend=False,margin=dict(l=10,r=10,t=20,b=10));fig.update_xaxes(showgrid=False);fig.update_yaxes(gridcolor='rgba(255,255,255,.05)');st.plotly_chart(fig,use_container_width=True,config={'displayModeBar':False})
 with r:st.markdown(f'<div class="visual"><div class="vcopy"><div class="micro">Next intelligence layer</div><div class="vbig">From meeting notes to decision memory.</div><div class="vnote">Audio → speakers → decisions → actions → risks → cross-meeting search.</div><div class="strip"><div class="mini"><b>{len(m.get("decisions",[]))}</b><span>decisions</span></div><div class="mini"><b>{len(m.get("actions",[]))}</b><span>actions</span></div><div class="mini"><b>{len(m.get("risks",[]))}</b><span>risks</span></div></div></div></div>',unsafe_allow_html=True)
st.markdown('<div class="foot">MEETINGLENS AI — FROM CONVERSATION TO CLARITY</div>',unsafe_allow_html=True)