from __future__ import annotations
import json, re
import pandas as pd
import plotly.express as px
import streamlit as st
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

st.set_page_config(page_title="MeetingLens AI", page_icon="◉", layout="wide", initial_sidebar_state="expanded")
HERO = "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1900&q=90"
SECOND = "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1500&q=88"

CSS = r'''<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap');
:root{--bg:#0c0e10;--panel:#171b1f;--text:#f3f0ea;--muted:#98a0a5;--line:rgba(255,255,255,.075);--bronze:#b99764;--gold:#d8bb88;--sage:#8ea69b;--steel:#8895a0}
*{box-sizing:border-box}html,body,[class*=css]{font-family:Inter,sans-serif}
.stApp{color:var(--text);background:radial-gradient(circle at 12% 8%,rgba(216,187,136,.055),transparent 23%),radial-gradient(circle at 87% 18%,rgba(142,166,155,.045),transparent 24%),linear-gradient(180deg,#0b0d0f 0%,#111417 54%,#0c0e10 100%)}
[data-testid=stHeader]{background:transparent}.block-container{max-width:1560px;padding-top:.9rem;padding-bottom:5rem}[data-testid=stSidebar]{background:linear-gradient(180deg,#111417,#0d0f11);border-right:1px solid var(--line)}
.stTabs [data-baseweb=tab-list]{gap:.5rem;border-bottom:1px solid var(--line);padding-bottom:.55rem}.stTabs [data-baseweb=tab]{font-size:.69rem;border-radius:11px;padding:.5rem .8rem;background:rgba(255,255,255,.018);border:1px solid var(--line);color:#9da4a8}.stTabs [aria-selected=true]{background:rgba(185,151,100,.09)!important;color:#d9c7ac!important;border-color:rgba(185,151,100,.21)!important}[data-testid=stFileUploader]{border:1px dashed rgba(216,187,136,.18);border-radius:16px;background:rgba(185,151,100,.015)}
.ambient{position:fixed;inset:0;pointer-events:none;overflow:hidden;z-index:0}.orb{position:absolute;border-radius:50%;filter:blur(80px);opacity:.10;animation:drift 20s ease-in-out infinite alternate}.o1{width:340px;height:340px;background:#b99764;left:-120px;top:8%}.o2{width:410px;height:410px;background:#6d7e77;right:-170px;top:28%;animation-duration:26s}.o3{width:280px;height:280px;background:#71808a;left:44%;bottom:-130px;animation-duration:22s}
@keyframes drift{to{transform:translate(36px,24px) scale(1.08)}}@keyframes up{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:none}}@keyframes pulse{0%,100%{opacity:.45;box-shadow:0 0 0 0 rgba(142,166,155,.15)}50%{opacity:1;box-shadow:0 0 0 7px transparent}}@keyframes sweep{0%,60%{transform:translateX(-130%)}82%,100%{transform:translateX(130%)}}@keyframes floaty{50%{transform:translateY(-8px)}}@keyframes wave{0%,100%{height:6px;opacity:.3}50%{height:34px;opacity:.95}}@keyframes ring{to{transform:rotate(360deg)}}@keyframes meter{from{transform:scaleX(.05)}to{transform:scaleX(1)}}@keyframes scan{0%{top:-15%}100%{top:110%}}@keyframes marquee{to{transform:translateX(-50%)}}
.brand{display:flex;align-items:center;gap:.75rem;margin:.15rem 0 1.3rem;animation:up .65s both}.logo{width:46px;height:46px;border-radius:15px;display:grid;place-items:center;border:1px solid rgba(216,187,136,.28);background:linear-gradient(145deg,#282d31,#171a1d);color:var(--gold);font-family:Manrope;font-weight:800;box-shadow:0 14px 34px rgba(0,0,0,.28)}.name{font-family:Manrope;font-size:1.08rem;font-weight:800;letter-spacing:-.035em}.name span{color:var(--gold)}.micro{font-size:.64rem;text-transform:uppercase;letter-spacing:.15em;color:#737b80;font-weight:700}.side{border:1px solid var(--line);background:rgba(255,255,255,.017);border-radius:17px;padding:1rem;margin-top:.85rem;transition:.25s}.side:hover{transform:translateY(-2px);border-color:rgba(216,187,136,.17)}.side strong{display:block;margin-top:.3rem;font-size:.84rem}.line{height:1px;background:linear-gradient(90deg,rgba(216,187,136,.45),transparent);margin-top:.7rem}
.top{display:flex;align-items:center;justify-content:space-between;padding:.35rem 0 1rem;border-bottom:1px solid var(--line);margin-bottom:1rem;animation:up .6s both}.eye{font-size:.68rem;text-transform:uppercase;letter-spacing:.15em;color:#7d858a;font-weight:700}.live{display:inline-flex;align-items:center;gap:.5rem;padding:.46rem .72rem;border-radius:999px;border:1px solid rgba(142,166,155,.2);background:rgba(142,166,155,.05);color:#becbc5;font-size:.72rem;font-weight:650}.dot{width:7px;height:7px;border-radius:50%;background:var(--sage);animation:pulse 2.2s infinite}
.hero{position:relative;display:grid;grid-template-columns:1.02fr .98fr;min-height:610px;overflow:hidden;border:1px solid var(--line);border-radius:34px;background:linear-gradient(135deg,#181c20,#111416);box-shadow:0 44px 120px rgba(0,0,0,.32);isolation:isolate;animation:up .85s both}.hero:before{content:'';position:absolute;inset:0;background:linear-gradient(120deg,transparent 20%,rgba(255,255,255,.028) 44%,transparent 58%);transform:translateX(-130%);animation:sweep 10s ease-in-out infinite;z-index:9;pointer-events:none}.hero:after{content:'';position:absolute;inset:14px;border:1px solid rgba(255,255,255,.035);border-radius:26px;pointer-events:none;z-index:8}
.hleft{position:relative;padding:4.8rem 3.7rem 3.6rem;display:flex;flex-direction:column;justify-content:center;z-index:3}.label{display:inline-flex;width:max-content;padding:.48rem .72rem;border-radius:999px;border:1px solid rgba(216,187,136,.2);background:rgba(185,151,100,.045);color:#d4bea0;font-size:.65rem;text-transform:uppercase;letter-spacing:.125em;font-weight:700;margin-bottom:1.25rem;animation:up .8s .1s both}.hero h1{font-family:Manrope;font-size:clamp(3.2rem,5.4vw,6.3rem);line-height:.89;letter-spacing:-.073em;margin:0;max-width:790px;font-weight:800;animation:up .85s .16s both}.hero h1 em{font-style:normal;color:var(--gold);font-weight:700;position:relative}.hero h1 em:after{content:'';position:absolute;left:0;right:0;bottom:-9px;height:1px;background:linear-gradient(90deg,var(--gold),transparent);transform-origin:left;animation:meter 1.2s .7s both}.hero p{font-size:1rem;line-height:1.8;color:#aeb4b7;max-width:610px;margin:1.35rem 0 0;animation:up .85s .25s both}.chips{display:flex;flex-wrap:wrap;gap:.55rem;margin-top:1.4rem;animation:up .85s .34s both}.chip{font-size:.72rem;color:#c8cccf;border:1px solid var(--line);border-radius:999px;padding:.46rem .68rem;background:rgba(255,255,255,.018);transition:.2s}.chip:hover{transform:translateY(-2px);border-color:rgba(216,187,136,.2);color:#e4d8c7}.signal{display:flex;align-items:center;gap:.8rem;margin-top:1.8rem;animation:up .85s .42s both}.signal span{font-size:.63rem;text-transform:uppercase;letter-spacing:.12em;color:#737c81;font-weight:700}.sigline{height:1px;flex:1;max-width:280px;background:linear-gradient(90deg,rgba(216,187,136,.85),rgba(142,166,155,.48),transparent);background-size:200% 100%;animation:sweep 5s linear infinite}
.hright{position:relative;min-height:610px;background-image:linear-gradient(180deg,rgba(14,16,18,.05),rgba(14,16,18,.74)),url('''+HERO+r''');background-size:106% auto;background-position:center;overflow:hidden;animation:herozoom 18s ease-in-out infinite alternate}@keyframes herozoom{to{background-size:114% auto}}.hright:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,#181c20 0%,rgba(24,28,32,.32) 18%,transparent 45%)}.scan{position:absolute;z-index:3;left:0;right:0;height:1px;background:linear-gradient(90deg,transparent,rgba(216,187,136,.35),transparent);box-shadow:0 0 24px rgba(216,187,136,.12);animation:scan 7s linear infinite}.hud{position:absolute;z-index:4;top:2rem;left:2rem;width:132px;height:132px;border-radius:50%;display:grid;place-items:center;background:rgba(13,15,17,.55);backdrop-filter:blur(16px);border:1px solid rgba(255,255,255,.1)}.hud:before{content:'';position:absolute;inset:8px;border-radius:50%;border:1px dashed rgba(216,187,136,.35);animation:ring 14s linear infinite}.hud:after{content:'';position:absolute;inset:20px;border-radius:50%;border:1px solid rgba(142,166,155,.18)}.hud .n{font-family:Manrope;font-size:1.75rem;font-weight:800}.hud .t{font-size:.52rem;text-transform:uppercase;letter-spacing:.12em;color:#899196;margin-top:-4px}
.float{position:absolute;z-index:5;border:1px solid rgba(255,255,255,.11);background:rgba(16,18,20,.72);backdrop-filter:blur(18px);box-shadow:0 18px 55px rgba(0,0,0,.28);border-radius:18px;padding:1rem;animation:floaty 6s ease-in-out infinite}.f1{top:2rem;right:2rem;width:205px}.f2{top:9.2rem;right:3.3rem;width:180px;animation-delay:-2s}.f3{bottom:2rem;left:2rem;right:2rem;animation-duration:7.5s;animation-delay:-1.4s}.flabel{font-size:.59rem;text-transform:uppercase;letter-spacing:.12em;color:#7e868b;font-weight:700}.fvalue{font-family:Manrope;font-size:1.34rem;font-weight:800;letter-spacing:-.045em;margin-top:.24rem}.fnote{font-size:.7rem;color:#aeb4b7;margin-top:.22rem}.wave{display:flex;align-items:center;gap:4px;height:40px;margin-top:.45rem}.wave i{display:block;width:3px;border-radius:99px;background:linear-gradient(180deg,var(--gold),var(--sage));animation:wave 1.7s ease-in-out infinite;opacity:.8}.wave i:nth-child(2n){animation-delay:.14s}.wave i:nth-child(3n){animation-delay:.29s}.wave i:nth-child(5n){animation-delay:.41s}
.ticker{margin:1rem 0 1.2rem;border-top:1px solid var(--line);border-bottom:1px solid var(--line);overflow:hidden;background:rgba(255,255,255,.008)}.ticktrack{display:flex;gap:2rem;width:max-content;padding:.72rem 0;animation:marquee 28s linear infinite}.tick{display:flex;align-items:center;gap:.55rem;color:#7f878c;font-size:.66rem;white-space:nowrap}.tick b{color:#c9b18d;font-weight:700}.tinywave{display:flex;gap:2px;align-items:center;height:14px}.tinywave i{width:2px;border-radius:9px;background:#8ea69b;animation:wave 1.5s infinite}.tinywave i:nth-child(2n){animation-delay:.2s}
.section{margin:1.5rem 0 .85rem;animation:up .7s both}.idx{font-size:.62rem;text-transform:uppercase;letter-spacing:.15em;color:#737b80;font-weight:700}.section h3{font-family:Manrope;font-size:1.18rem;margin:.2rem 0 0;letter-spacing:-.03em}.section p{font-size:.76rem;color:#7f878c;margin:.25rem 0 0}
.kpi{position:relative;overflow:hidden;border:1px solid var(--line);border-radius:21px;padding:1.2rem 1.22rem;min-height:150px;background:linear-gradient(180deg,rgba(28,32,36,.92),rgba(20,23,26,.94));transition:.28s;animation:up .7s both}.kpi:hover{transform:translateY(-6px);border-color:rgba(216,187,136,.2);box-shadow:0 24px 58px rgba(0,0,0,.24)}.kpi:after{content:'';position:absolute;inset:0;background:linear-gradient(115deg,transparent 24%,rgba(255,255,255,.035) 48%,transparent 68%);transform:translateX(-130%);transition:.85s}.kpi:hover:after{transform:translateX(130%)}.kl{font-size:.62rem;text-transform:uppercase;letter-spacing:.12em;color:#7f878c;font-weight:700}.kv{font-family:Manrope;font-size:2.12rem;font-weight:800;letter-spacing:-.058em;margin:.4rem 0 .18rem}.kn{font-size:.74rem;color:#8e969b}.badge{position:absolute;right:1rem;top:1rem;width:7px;height:7px;border-radius:50%;background:var(--bronze);box-shadow:0 0 0 5px rgba(185,151,100,.05)}.meter{height:3px;border-radius:99px;background:rgba(255,255,255,.05);overflow:hidden;margin-top:.85rem}.meter span{display:block;height:100%;border-radius:99px;background:linear-gradient(90deg,var(--bronze),var(--sage));transform-origin:left;animation:meter 1.2s .25s both}
.story{display:grid;grid-template-columns:repeat(5,1fr);gap:.7rem;margin:1rem 0}.storycard{position:relative;border:1px solid var(--line);border-radius:18px;padding:1rem;background:rgba(255,255,255,.014);min-height:120px;overflow:hidden;transition:.25s}.storycard:hover{transform:translateY(-4px);border-color:rgba(216,187,136,.18)}.storycard:before{content:'';position:absolute;left:0;top:0;width:100%;height:2px;background:linear-gradient(90deg,var(--bronze),transparent)}.storynum{font-size:.56rem;color:#737b80;letter-spacing:.14em;text-transform:uppercase}.storytitle{font-family:Manrope;font-weight:750;margin-top:.45rem;font-size:.95rem}.storynote{font-size:.7rem;color:#90979b;margin-top:.28rem;line-height:1.45}
.panel{position:relative;overflow:hidden;border:1px solid var(--line);border-radius:23px;background:linear-gradient(180deg,rgba(25,29,33,.86),rgba(20,23,26,.88));padding:1.35rem;box-shadow:inset 0 1px 0 rgba(255,255,255,.02);animation:up .78s both}.pt{font-family:Manrope;font-size:1.04rem;font-weight:760;letter-spacing:-.025em}.ps{font-size:.75rem;color:#858d92;margin:.26rem 0 1rem}.moment{display:grid;grid-template-columns:60px 1fr;gap:.82rem;padding:.9rem .18rem;border-bottom:1px solid rgba(255,255,255,.055);transition:.22s}.moment:last-child{border-bottom:0}.moment:hover{padding-left:.55rem;background:linear-gradient(90deg,rgba(185,151,100,.035),transparent)}.time{font-size:.65rem;color:var(--gold);padding-top:.18rem;font-weight:700}.mh{font-size:.82rem;font-weight:650}.tag{display:inline-block;font-size:.54rem;text-transform:uppercase;letter-spacing:.07em;border:1px solid rgba(185,151,100,.16);background:rgba(185,151,100,.05);color:#cbb18b;padding:.18rem .38rem;border-radius:999px;margin-left:.32rem}.mt{font-size:.76rem;line-height:1.58;color:#9ea5aa;margin-top:.24rem}.decision{padding:.9rem .96rem;margin:.72rem 0;border-radius:16px;background:rgba(255,255,255,.015);border:1px solid rgba(255,255,255,.055);transition:.22s}.decision:hover{transform:translateX(4px);border-color:rgba(216,187,136,.16)}.conf,.owner{display:inline-flex;font-size:.57rem;margin-top:.45rem;padding:.2rem .4rem;border-radius:999px;border:1px solid rgba(142,166,155,.14);color:#b8c9c1;background:rgba(142,166,155,.055)}.owner{margin-left:.35rem;border-color:rgba(136,149,160,.13);color:#b8c0c8;background:rgba(136,149,160,.055)}.confbar{height:4px;background:rgba(255,255,255,.05);border-radius:99px;overflow:hidden;margin-top:.55rem}.confbar span{display:block;height:100%;background:linear-gradient(90deg,var(--bronze),var(--sage));animation:meter 1.2s both}
.visual{position:relative;min-height:360px;border-radius:23px;overflow:hidden;background-image:linear-gradient(180deg,rgba(14,16,18,.06),rgba(14,16,18,.84)),url('''+SECOND+r''');background-size:104% auto;background-position:center;animation:vzoom 16s ease-in-out infinite alternate}@keyframes vzoom{to{background-size:112% auto}}.visual:after{content:'';position:absolute;inset:0;background:linear-gradient(120deg,transparent 35%,rgba(255,255,255,.035),transparent 65%);transform:translateX(-120%);animation:sweep 11s infinite}.vcopy{position:absolute;z-index:2;left:1.3rem;right:1.3rem;bottom:1.2rem}.vbig{font-family:Manrope;font-size:1.55rem;font-weight:800;letter-spacing:-.045em;line-height:1.08}.vnote{font-size:.74rem;color:#b9bec1;margin-top:.42rem}.footer{text-align:center;color:#596065;font-size:.63rem;margin-top:3rem;padding-top:1.25rem;border-top:1px solid rgba(255,255,255,.045)}
@media(max-width:1100px){.hero{grid-template-columns:1fr}.hright{min-height:470px}.hleft{padding:3.2rem 1.8rem}.story{grid-template-columns:1fr 1fr}.hud{display:none}}@media(max-width:680px){.float.f1,.float.f2{display:none}.story{grid-template-columns:1fr}.hero h1{font-size:clamp(2.9rem,14vw,4.6rem)}}
</style>'''
st.markdown(CSS, unsafe_allow_html=True)
st.markdown('<div class="ambient"><div class="orb o1"></div><div class="orb o2"></div><div class="orb o3"></div></div>', unsafe_allow_html=True)

DEMO={"title":"Product Intelligence Weekly","duration_min":47,"summary":"The team aligned on launch readiness, analytics fixes, and ownership for the next release.","participants":[{"name":"Maya","talk_pct":31},{"name":"Noah","talk_pct":27},{"name":"Lina","talk_pct":23},{"name":"Omar","talk_pct":19}],"segments":[{"minute":3,"speaker":"Maya","kind":"context","text":"We need to leave today with one launch decision and clear owners.","sentiment":"neutral"},{"minute":12,"speaker":"Noah","kind":"risk","text":"The analytics patch is still blocking our final validation.","sentiment":"negative"},{"minute":21,"speaker":"Lina","kind":"decision","text":"We will keep the Friday release if analytics passes tomorrow morning.","sentiment":"positive"},{"minute":29,"speaker":"Omar","kind":"action","text":"I will own the analytics validation and post results before noon.","sentiment":"positive"},{"minute":38,"speaker":"Maya","kind":"decision","text":"Support will receive the rollout notes before the release window.","sentiment":"positive"}],"decisions":[{"title":"Keep Friday release target","detail":"Conditional on analytics validation tomorrow morning.","confidence":.94},{"title":"Share rollout notes with Support","detail":"Notes must land before the release window.","confidence":.91}],"actions":[{"task":"Validate analytics patch","owner":"Omar","due":"Tomorrow 12:00","status":"Open"},{"task":"Prepare rollout notes","owner":"Maya","due":"Friday 09:00","status":"Open"}],"risks":[{"title":"Analytics validation delay","severity":"Medium"}]}
AN=SentimentIntensityAnalyzer()
def classify(text):
    s=AN.polarity_scores(text or "")["compound"]; return "positive" if s>=.18 else "negative" if s<=-.18 else "neutral"
def health(m):
    p=[x.get("talk_pct",0) for x in m.get("participants",[])]; balance=80 if not p else max(0,100-(max(p)-min(p))*2); clarity=min(100,55+len(m.get("decisions",[]))*12+len(m.get("actions",[]))*7); seg=m.get("segments",[]); pos=sum(1 for x in seg if x.get("sentiment")=="positive"); sentiment=int(pos/max(1,len(seg))*100); return {"overall":round(balance*.3+clarity*.45+sentiment*.25),"clarity":int(clarity),"balance":int(balance),"sentiment":sentiment}
def tokens(t): return {x for x in re.findall(r"[a-zA-Z0-9']+",(t or "").lower()) if len(x)>2}
def search_meeting(m,q):
    q=tokens(q); out=[]
    for s in m.get("segments",[]):
        score=len(q & tokens(" ".join([s.get("speaker",""),s.get("kind",""),s.get("text","")])))
        if score: out.append((score,s))
    return [s for _,s in sorted(out,key=lambda x:-x[0])]
def load_upload(f):
    try:
        d=json.load(f)
        for s in d.get("segments",[]): s["sentiment"]=s.get("sentiment") or classify(s.get("text",""))
        return d,None
    except Exception as e: return None,str(e)

with st.sidebar:
    st.markdown('<div class="brand"><div class="logo">M</div><div class="name">MeetingLens <span>AI</span></div></div>',unsafe_allow_html=True)
    st.markdown('<div class="micro">Conversation intelligence</div>',unsafe_allow_html=True)
    uploaded=st.file_uploader("Upload meeting JSON",type=["json"])
    st.markdown('<div class="side"><div class="micro">Mode</div><strong>Decision intelligence</strong><div class="line"></div></div>',unsafe_allow_html=True)
    st.markdown('<div class="side"><div class="micro">Experience</div><strong>Cinematic analytics workspace</strong></div>',unsafe_allow_html=True)

meeting=DEMO
if uploaded:
    candidate,err=load_upload(uploaded)
    if candidate: meeting=candidate; st.sidebar.success("Meeting loaded")
    else: st.sidebar.error(f"Invalid JSON: {err}")

st.markdown('<div class="top"><div class="eye">Meeting intelligence / live workspace</div><div class="live"><span class="dot"></span> engine online</div></div>',unsafe_allow_html=True)
tabs=st.tabs(["Overview","Meeting Analyzer","Knowledge Search","Insights"])

with tabs[0]:
    h=health(meeting); bars=''.join('<i></i>' for _ in range(22))
    st.markdown(f'''<div class="hero"><div class="hleft"><div class="label">◉ AI meeting intelligence</div><h1>Turn conversation into <em>clarity.</em></h1><p>{meeting.get("summary","Turn conversations into decisions, ownership, and searchable memory.")}</p><div class="chips"><span class="chip">{meeting.get("title","Meeting")}</span><span class="chip">{meeting.get("duration_min",0)} min</span><span class="chip">{len(meeting.get("participants",[]))} participants</span></div><div class="signal"><span>decision signal active</span><div class="sigline"></div></div></div><div class="hright"><div class="scan"></div><div class="hud"><div><div class="n">{h["overall"]}</div><div class="t">health score</div></div></div><div class="float f1"><div class="flabel">Latest decision</div><div class="fvalue">Release target</div><div class="fnote">Conditional approval detected</div></div><div class="float f2"><div class="flabel">Open risk</div><div class="fvalue">{len(meeting.get("risks",[]))}</div><div class="fnote">Needs follow-up</div></div><div class="float f3"><div class="flabel">Conversation pulse</div><div class="wave">{bars}</div></div></div></div>''',unsafe_allow_html=True)
    items=["03:00 · context established","12:00 · blocker detected","21:00 · decision captured","29:00 · owner assigned","38:00 · rollout decision","47:00 · meeting closed"]
    tick=''.join(f'<div class="tick"><div class="tinywave"><i></i><i></i><i></i></div><b>LIVE</b>{x}</div>' for x in items*2)
    st.markdown(f'<div class="ticker"><div class="ticktrack">{tick}</div></div>',unsafe_allow_html=True)
    st.markdown('<div class="section"><div class="idx">01 / Meeting signal</div><h3>What this conversation produced</h3><p>Clarity, commitments, ownership and unresolved risk in one view.</p></div>',unsafe_allow_html=True)
    vals=[("Meeting health",f'{h["overall"]}/100',"Clarity, balance & tone",h["overall"]),("Decisions",len(meeting.get("decisions",[])),"Captured commitments",88),("Action items",len(meeting.get("actions",[])),"Owners & deadlines",82),("Risks",len(meeting.get("risks",[])),"Needs follow-up",58)]
    cols=st.columns(4)
    for c,(a,b,n,meter) in zip(cols,vals):
        with c: st.markdown(f'<div class="kpi"><span class="badge"></span><div class="kl">{a}</div><div class="kv">{b}</div><div class="kn">{n}</div><div class="meter"><span style="width:{meter}%"></span></div></div>',unsafe_allow_html=True)
    st.markdown('<div class="section"><div class="idx">02 / Intelligence flow</div><h3>From speech to organizational memory</h3><p>The product story in five steps.</p></div>',unsafe_allow_html=True)
    st.markdown('''<div class="story"><div class="storycard"><div class="storynum">01</div><div class="storytitle">Conversation</div><div class="storynote">Audio and transcript enter the system.</div></div><div class="storycard"><div class="storynum">02</div><div class="storytitle">Signal</div><div class="storynote">Key moments, sentiment and friction are detected.</div></div><div class="storycard"><div class="storynum">03</div><div class="storytitle">Decision</div><div class="storynote">Commitments are extracted with confidence.</div></div><div class="storycard"><div class="storynum">04</div><div class="storytitle">Ownership</div><div class="storynote">Tasks are linked to people and deadlines.</div></div><div class="storycard"><div class="storynum">05</div><div class="storytitle">Memory</div><div class="storynote">Meetings become searchable organizational knowledge.</div></div></div>''',unsafe_allow_html=True)
    c1,c2=st.columns([1.2,.8])
    with c1:
        st.markdown('<div class="panel"><div class="pt">Key moments</div><div class="ps">The moments that changed the direction of the meeting.</div>',unsafe_allow_html=True)
        for s in meeting.get("segments",[]): st.markdown(f'<div class="moment"><div class="time">{str(s.get("minute",0)).zfill(2)}:00</div><div><div class="mh">{s.get("speaker","Speaker")} <span class="tag">{s.get("kind","moment")}</span></div><div class="mt">{s.get("text","")}</div></div></div>',unsafe_allow_html=True)
        st.markdown('</div>',unsafe_allow_html=True)
    with c2:
        st.markdown('<div class="panel"><div class="pt">Speaker balance</div><div class="ps">Share of speaking time.</div>',unsafe_allow_html=True)
        frame=pd.DataFrame(meeting.get("participants",[]))
        if not frame.empty:
            fig=px.pie(frame,values="talk_pct",names="name",hole=.76,color_discrete_sequence=["#d8bb88","#8ea69b","#8895a0","#b99764"]); fig.update_layout(height=330,margin=dict(l=0,r=0,t=0,b=0),showlegend=False,paper_bgcolor="rgba(0,0,0,0)",font_color="#f3f0ea"); st.plotly_chart(fig,use_container_width=True,config={"displayModeBar":False})
        st.markdown('</div>',unsafe_allow_html=True)
with tabs[1]:
    st.subheader("Meeting Analyzer"); st.caption("Inspect decisions, actions, risks, and transcript moments from the current meeting."); c1,c2=st.columns(2)
    with c1:
        st.markdown('<div class="panel"><div class="pt">Decisions captured</div><div class="ps">Commitments with confidence.</div>',unsafe_allow_html=True)
        for d in meeting.get("decisions",[]):
            pct=round(float(d.get("confidence",0))*100); st.markdown(f'<div class="decision"><strong>✓ {d.get("title","Decision")}</strong><div class="mt">{d.get("detail","")}</div><span class="conf">{pct}% confidence</span><div class="confbar"><span style="width:{pct}%"></span></div></div>',unsafe_allow_html=True)
        st.markdown('</div>',unsafe_allow_html=True)
    with c2:
        st.markdown('<div class="panel"><div class="pt">Action ownership</div><div class="ps">What needs to happen next and who owns it.</div>',unsafe_allow_html=True)
        for x in meeting.get("actions",[]): st.markdown(f'<div class="decision"><strong>{x.get("task","Task")}</strong><span class="owner">{x.get("owner","Unassigned")}</span><div class="mt">Due {x.get("due","TBD")} · {x.get("status","Open")}</div></div>',unsafe_allow_html=True)
        st.markdown('</div>',unsafe_allow_html=True)
    st.dataframe(pd.DataFrame(meeting.get("segments",[])),use_container_width=True,hide_index=True)
with tabs[2]:
    st.subheader("Knowledge Search"); st.caption("Search the current meeting memory for topics, owners, decisions, or risks."); q=st.text_input("Ask the meeting memory",placeholder="e.g. analytics patch, Friday release, Support...")
    if q:
        results=search_meeting(meeting,q)
        if not results: st.info("No matching moment found.")
        for s in results: st.markdown(f'<div class="panel"><div class="pt">{s.get("speaker","Speaker")} · {s.get("minute",0)}:00 <span class="tag">{s.get("kind","moment")}</span></div><div class="mt">{s.get("text","")}</div></div>',unsafe_allow_html=True)
    else: st.info("Type a topic above to search inside the meeting.")
with tabs[3]:
    st.subheader("Insights"); st.caption("A compact read on clarity, balance, tone, and follow-through."); h=health(meeting); c1,c2,c3,c4=st.columns(4); c1.metric("Overall",f'{h["overall"]}/100'); c2.metric("Clarity",f'{h["clarity"]}/100'); c3.metric("Balance",f'{h["balance"]}/100'); c4.metric("Positive tone",f'{h["sentiment"]}%')
    left,right=st.columns([.62,.38])
    with left:
        seg=pd.DataFrame(meeting.get("segments",[]))
        if not seg.empty:
            counts=seg["sentiment"].value_counts().rename_axis("sentiment").reset_index(name="count"); fig=px.bar(counts,x="sentiment",y="count",color="sentiment",color_discrete_map={"positive":"#8ea69b","neutral":"#8895a0","negative":"#b99764"}); fig.update_layout(height=360,paper_bgcolor="rgba(0,0,0,0)",plot_bgcolor="rgba(0,0,0,0)",font_color="#f3f0ea",showlegend=False); st.plotly_chart(fig,use_container_width=True,config={"displayModeBar":False})
    with right: st.markdown('<div class="visual"><div class="vcopy"><div class="micro">Next intelligence layer</div><div class="vbig">From meeting notes to decision memory.</div><div class="vnote">Audio → speakers → decisions → actions → risks → cross-meeting search.</div></div></div>',unsafe_allow_html=True)
st.markdown('<div class="footer">MEETINGLENS AI — FROM CONVERSATION TO CLARITY</div>',unsafe_allow_html=True)
