[theme]
base = "dark"
primaryColor = "#C7AD82"
backgroundColor = "#090B0E"
secondaryBackgroundColor = "#12161A"
textColor = "#F2F0EB"
font = "sans serif"

[server]
headless = true
maxUploadSize = 100
